import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

const ROOT = new URL('../', import.meta.url);
const SANITIZER = fileURLToPath(new URL('sanitize-sbom.mjs', import.meta.url));
const source = readFileSync(new URL('sbom/sbom.json', ROOT), 'utf8');
const bom = JSON.parse(source);
const manifest = JSON.parse(readFileSync(new URL('package.json', ROOT), 'utf8'));
const licenseEvidence = JSON.parse(
  readFileSync(new URL('scripts/data/sbom-license-evidence.json', ROOT), 'utf8'),
);

function flatten(components = []) {
  return components.flatMap((component) => [component, ...flatten(component.components)]);
}

function strings(value, trail = '$') {
  if (Array.isArray(value)) {
    return value.flatMap((item, index) => strings(item, `${trail}[${String(index)}]`));
  }
  if (value === null || typeof value !== 'object') {
    return typeof value === 'string' ? [{ trail, value }] : [];
  }
  return Object.entries(value).flatMap(([key, nested]) => strings(nested, `${trail}.${key}`));
}

describe('the published software bill of materials', () => {
  it('is a populated CycloneDX 1.6 document generated by cdxgen', () => {
    assert.equal(bom.bomFormat, 'CycloneDX');
    assert.equal(bom.specVersion, '1.6');
    assert.equal(bom.version, 1);
    assert.match(
      bom.serialNumber,
      /^urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    );
    assert.match(bom.metadata.timestamp, /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/);
    assert.ok(Number.isFinite(Date.parse(bom.metadata.timestamp)));
    assert.ok(bom.components.length > 100, 'the dependency inventory is unexpectedly empty');

    const generator = bom.metadata.tools.components.find(
      (component) => component.group === '@cyclonedx' && component.name === 'cdxgen',
    );
    assert.ok(generator, 'the SBOM does not identify its generator');
    assert.equal(generator.version, '12.8.4');
    assert.equal(generator.purl, 'pkg:npm/%40cyclonedx/cdxgen@12.8.4');
  });

  it('identifies the current DarkRoute release and all pnpm workspace packages', () => {
    const root = bom.metadata.component;
    assert.equal(root.type, 'application');
    assert.equal(root.name, manifest.name);
    assert.equal(root.version, manifest.version);
    assert.equal(root.purl, `pkg:npm/${manifest.name}@${manifest.version}`);

    const workspaces = new Map(
      root.components.map((component) => [`${component.group}/${component.name}`, component]),
    );
    for (const name of ['@fwm/pwa', '@fwm/api-client', '@fwm/core']) {
      assert.equal(workspaces.get(name)?.version, manifest.version, `${name} is missing or stale`);
    }
  });

  it('contains the pinned Meshtastic dependency', () => {
    const meshtastic = bom.components.find(
      (component) => component.group === '@meshtastic' && component.name === 'js',
    );

    assert.ok(meshtastic, '@meshtastic/js is missing from the SBOM');
    assert.equal(meshtastic.version, '2.6.0-0');
    assert.equal(meshtastic.purl, 'pkg:npm/%40meshtastic/js@2.6.0-0');

    const protobufs = bom.components.find(
      (component) => component.purl === 'pkg:npm/%40jsr/meshtastic__protobufs@2.7.26',
    );
    assert.ok(protobufs, '@jsr/meshtastic__protobufs is missing from the SBOM');
    assert.deepEqual(
      protobufs.licenses?.map((entry) => entry.license?.id),
      ['GPL-3.0-only'],
      'the JSR package omits its package.json license; preserve the evidenced release licence',
    );
    assert.ok(
      protobufs.externalReferences?.some(
        (reference) =>
          reference.type === 'license' &&
          reference.url === 'https://github.com/meshtastic/protobufs/blob/v2.7.26/LICENSE',
      ),
      'the exact upstream licence evidence is missing',
    );
    assert.ok(
      protobufs.properties?.some(
        (property) =>
          property.name === 'darkroute:license-evidence' &&
          property.value.includes('LICENSE bundled in the exact 2.7.26 tarball'),
      ),
      'the package-metadata gap is not documented in the SBOM',
    );
  });

  it('contains the exact deployment CLI selected by the lockfile', () => {
    const wrangler = bom.components.find(
      (component) => component.purl === 'pkg:npm/wrangler@4.128.0',
    );
    assert.ok(wrangler, 'the pinned Wrangler deployment tool is missing from the SBOM');
    assert.equal(wrangler.version, manifest.devDependencies.wrangler);
  });

  it('licenses every resolved third-party component with hash-bound evidence for omissions', () => {
    assert.equal(bom.components.length, 778);
    assert.deepEqual(
      bom.components.filter(
        (component) => !Array.isArray(component.licenses) || component.licenses.length === 0,
      ),
      [],
    );

    assert.equal(licenseEvidence.schema, 'darkroute-sbom-license-evidence/v1');
    assert.equal(licenseEvidence.registry, 'https://registry.npmjs.org/');
    assert.equal(licenseEvidence.components.length, 201);
    const components = new Map(
      bom.components.map((component) => [component['bom-ref'], component]),
    );
    for (const entry of licenseEvidence.components) {
      const component = components.get(entry.ref);
      assert.ok(component, `licence evidence names an unknown component: ${entry.ref}`);
      const digest = component.hashes.find((hash) => hash.alg === 'SHA-512')?.content;
      assert.equal(
        Buffer.from(entry.integrity.slice('sha512-'.length), 'base64').toString('hex'),
        digest,
        `${entry.ref} evidence is not bound to the resolved package bytes`,
      );
      const choice = component.licenses[0];
      assert.equal(choice.expression ?? choice.license?.id, entry.license);
      assert.ok(
        component.properties?.some(
          (property) =>
            property.name === 'darkroute:license-evidence' && property.value === entry.metadataUrl,
        ),
        `${entry.ref} has no exact-version metadata evidence`,
      );
    }

    const libvips = bom.components.filter(
      (component) => component.group === '@img' && component.name.startsWith('sharp-libvips-'),
    );
    assert.equal(libvips.length, 10);
    for (const component of libvips) {
      assert.equal(
        component.licenses[0]?.license?.id ?? component.licenses[0]?.expression,
        'LGPL-3.0-or-later',
      );
    }
  });

  it('has unique component references and a complete dependency graph', () => {
    const components = [...flatten([bom.metadata.component]), ...flatten(bom.components)];
    const refs = components.map((component) => component['bom-ref']);
    const known = new Set(refs);

    assert.equal(known.size, refs.length, 'component bom-ref values must be unique');
    assert.ok(refs.every((ref) => typeof ref === 'string' && ref.length > 0));
    assert.equal(bom.dependencies.length, known.size);

    const dependencyRefs = new Set();
    const dependencyMap = new Map();
    let dependencyEdges = 0;
    for (const dependency of bom.dependencies) {
      assert.ok(known.has(dependency.ref), `unknown dependency ref: ${dependency.ref}`);
      assert.ok(!dependencyRefs.has(dependency.ref), `duplicate dependency ref: ${dependency.ref}`);
      dependencyRefs.add(dependency.ref);
      dependencyMap.set(dependency.ref, dependency.dependsOn);
      dependencyEdges += dependency.dependsOn.length;
      assert.ok(Array.isArray(dependency.dependsOn));
      for (const target of dependency.dependsOn) {
        assert.ok(known.has(target), `${dependency.ref} depends on unknown ref: ${target}`);
      }
    }
    assert.equal(
      dependencyEdges,
      1_645,
      'graph must match 1,642 pnpm-lock edges plus 3 workspace aggregation edges',
    );

    const rootRef = bom.metadata.component['bom-ref'];
    const reachable = new Set([rootRef]);
    const queue = [rootRef];
    while (queue.length > 0) {
      for (const target of dependencyMap.get(queue.shift())) {
        if (reachable.has(target)) continue;
        reachable.add(target);
        queue.push(target);
      }
    }
    assert.equal(
      reachable.size,
      known.size,
      `${String(known.size - reachable.size)} SBOM components are disconnected from the root`,
    );

    const wranglerRef = 'pkg:npm/wrangler@4.128.0';
    const miniflareRef = 'pkg:npm/miniflare@5.20260831.0-alpha';
    const sharpRef = 'pkg:npm/sharp@0.35.2';
    const libvipsRefs = [
      'pkg:npm/@img/sharp-libvips-linux-x64@1.3.1',
      'pkg:npm/@img/sharp-libvips-linuxmusl-x64@1.3.1',
    ];
    assert.ok(dependencyMap.get(rootRef).includes(wranglerRef));
    assert.ok(dependencyMap.get(wranglerRef).includes(miniflareRef));
    assert.ok(dependencyMap.get(miniflareRef).includes(sharpRef));
    for (const libvipsRef of libvipsRefs) {
      assert.ok(dependencyMap.get(sharpRef).includes(libvipsRef));
    }
    const sharpWasmRef = 'pkg:npm/@img/sharp-wasm32@0.35.2';
    assert.ok(!dependencyMap.get(sharpRef).includes(sharpWasmRef));
    assert.ok(dependencyMap.get('pkg:npm/@img/sharp-freebsd-wasm32@0.35.2').includes(sharpWasmRef));
  });

  it('contains no values from the checked-in placeholder', () => {
    assert.doesNotMatch(source, /<your org>|<tool name>|"name": "project-name"/i);
    assert.notEqual(bom.serialNumber, 'urn:uuid:00000000-0000-0000-0000-000000000000');
    assert.ok(bom.components.length > 0);
  });

  it('contains no generator-internal checkout paths', () => {
    for (const { trail, value } of strings(bom)) {
      assert.doesNotMatch(value, /^\/(?!\/)/, `POSIX absolute path at ${trail}`);
      assert.doesNotMatch(value, /^[a-z]:[\\/]/i, `Windows absolute path at ${trail}`);
      assert.doesNotMatch(value, /^\\\\/, `UNC path at ${trail}`);
      assert.doesNotMatch(value, /flockyswatchingme/i, `private checkout name at ${trail}`);
    }

    assert.doesNotMatch(source, /(?:internal:)?LocalNodeModulesPath/);
  });

  it('is reproducibly repaired from the pnpm lockfile and sanitizes idempotently', () => {
    const directory = mkdtempSync(join(tmpdir(), 'darkroute-sbom-test-'));
    const candidatePath = join(directory, 'sbom.json');
    try {
      const candidate = JSON.parse(source);
      const rootDependency = candidate.dependencies.find(
        (dependency) => dependency.ref === candidate.metadata.component['bom-ref'],
      );
      rootDependency.dependsOn = rootDependency.dependsOn.filter(
        (reference) => reference !== 'pkg:npm/wrangler@4.128.0',
      );
      const sharpDependency = candidate.dependencies.find(
        (dependency) => dependency.ref === 'pkg:npm/sharp@0.35.2',
      );
      sharpDependency.dependsOn.push('pkg:npm/@img/sharp-wasm32@0.35.2');
      writeFileSync(candidatePath, `${JSON.stringify(candidate, null, 2)}\n`);

      const first = spawnSync(process.execPath, [SANITIZER, candidatePath], {
        cwd: fileURLToPath(ROOT),
        encoding: 'utf8',
      });
      assert.equal(first.status, 0, first.stderr);
      assert.match(first.stdout, /reconciled 2 dependency edges/);
      assert.equal(readFileSync(candidatePath, 'utf8'), source);

      const second = spawnSync(process.execPath, [SANITIZER, candidatePath], {
        cwd: fileURLToPath(ROOT),
        encoding: 'utf8',
      });
      assert.equal(second.status, 0, second.stderr);
      assert.match(second.stdout, /reconciled 0 dependency edges/);
      assert.equal(readFileSync(candidatePath, 'utf8'), source);
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });
});
